### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by carlosdarienvizcaino** [chausen/TigerZoneServer#3]
TEAMD joined
TEAMA joined
These are the tournament players TEAMD
These are the tournament players TEAMA
BEGIN ROUND 1 OF 1
BEGIN ROUND 1 OF 1
Number of active threads from the given thread: 9
YOUR OPPONENT IS PLAYER TEAMA
STARTING TILE IS TLTJ- AT 0 0 0
THE REMAINING 76 TILES ARE [ JJJJX JLTT- LLLL- TJJT- TJTJ- LLJJ- LJLJ- LLJJ- TLLLC TLLTB TJJT- JLLL- LJJJ- TLJT- TLTTP TJTJ- TLTJ- LJJJ- JLTTB JLLJ- LLJJ- JLLL- TJJT- LJTJD TLLT- TJJT- TJJT- LLJJ- TJTJ- TJTT- TLTJ- TJJT- JJJJX TLLTB TJTT- JLTTB TJTT- TLTTP JJJJX TTTT- TJTJ- JJJJX TLJTP TLLT- TLTJD TLLLC TLLL- JLJL- TLLT- TLTJD LJLJ- TJTT- JLJL- LJTJ- TJJT- JJTJX TJTJ- JLLJ- JJTJX LJTJD LJJJ- LLJJ- TJJT- JLLL- LJJJ- TLJTP LJJJ- TJTJ- JLLL- TLTT- TJTJ- LJLJ- JLJL- TJJT- JJJJ- TJTJ- ]
MATCH BEGINS IN 10 SECONDS
YOUR OPPONENT IS PLAYER TEAMD
STARTING TILE IS TLTJ- AT 0 0 0
THE REMAINING 76 TILES ARE [ JJJJX JLTT- LLLL- TJJT- TJTJ- LLJJ- LJLJ- LLJJ- TLLLC TLLTB TJJT- JLLL- LJJJ- TLJT- TLTTP TJTJ- TLTJ- LJJJ- JLTTB JLLJ- LLJJ- JLLL- TJJT- LJTJD TLLT- TJJT- TJJT- LLJJ- TJTJ- TJTT- TLTJ- TJJT- JJJJX TLLTB TJTT- JLTTB TJTT- TLTTP JJJJX TTTT- TJTJ- JJJJX TLJTP TLLT- TLTJD TLLLC TLLL- JLJL- TLLT- TLTJD LJLJ- TJTT- JLJL- LJTJ- TJJT- JJTJX TJTJ- JLLJ- JJTJX LJTJD LJJJ- LLJJ- TJJT- JLLL- LJJJ- TLJTP LJJJ- TJTJ- JLLL- TLTT- TJTJ- LJLJ- JLJL- TJJT- JJJJ- TJTJ- ]
MATCH BEGINS IN 10 SECONDS
Exception in thread "Thread-8" java.lang.UnsupportedOperationException
	at java.util.AbstractList.remove(AbstractList.java:161)
	at java.util.AbstractList$Itr.remove(AbstractList.java:374)
	at java.util.AbstractCollection.remove(AbstractCollection.java:293)
	at com.tigerzone.fall2016.area.AreaBuilder.updateTerrainNodes(AreaBuilder.java:159)
	at com.tigerzone.fall2016.area.AreaBuilder.buildNorthFace(AreaBuilder.java:84)
	at com.tigerzone.fall2016.area.AreaBuilder.build(AreaBuilder.java:35)
	at com.tigerzone.fall2016.area.AreaManager.addTile(AreaManager.java:79)
	at com.tigerzone.fall2016.gamesystem.GameSystem.receiveTurn(GameSystem.java:133)
	at com.tigerzone.fall2016.ports.IOPort.receiveTurnPlace(IOPort.java:164)
	at com.tigerzone.fall2016.ports.IOPort.receiveTurn(IOPort.java:109)
	at com.tigerzone.fall2016server.tournament.Game.receiveTurn(Game.java:60)
	at com.tigerzone.fall2016server.tournament.Match.playMatch(Match.java:124)
	at com.tigerzone.fall2016server.tournament.Match.run(Match.java:49)

**Comment by chausen** [comment]
In `BoardTile` we are creating Lists in this way: 
`new ArrayList<>(Arrays.asList(1,2,3,4,5,6,7,8,9)`

`Arrays.asList()` returns an immutable list, but passing it as input to a new `ArrayList` makes a mutable `ArrayList`. However, this exception is still thrown when an element is removed in (`AreaBuilder.java` -> `updateTerrainNodes()`. We have added a `catch` for this exception that does nothing, because we do not intend for the `ArrayList` to be immutable.
